name: CI
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - run: msbuild -v:m -r
    - uses: actions/upload-artifact@v2
      with:
        path: MisakaTranslator-WPF/bin
    - name: InferSharp
    - uses: microsoft/infersharpaction@v1.4
      with:
        binary-path: MisakaTranslator-WPF/bin

      
