name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: microsoft/setup-msbuild@v1
    - run: msbuild -v:m -r
    - uses: actions/upload-artifact@v2
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v1.2
      with:
        binary-path: MisakaTranslator-WPF/bin

